### ISSUE TITLE
Moving inTopic to a var

### ISSUE THREAD

**Issue by Paul-Reed** [Paul-Reed/imroy_mqtt_esp#1]
Thanks @lights0123 for suggesting @Imroy 's fork of pubsubclient, I've now updated most of my devices, and successfully using QoS1.
However, I'm having difficulties with one device which uses the MQTT `inTopic`, to control certain functions.
In lines [27 to 28](https://github.com/Paul-Reed/imroy_mqtt_esp/blob/master/imroy_mqtt_esp.ino#L27-L28) I attempt to read the inTopic message, and save it to load.
In lines [29 - 32](https://github.com/Paul-Reed/imroy_mqtt_esp/blob/master/imroy_mqtt_esp.ino#L29-L32) I use the value of `load` to trigger other functions.

Except it doesn't work, as I'm comparing a string with an int, which of course will not work.

Should `load` be declared as a String in the first place?

All of the incoming `inTopic` messages with be numbers such as 10 etc, and no text.

**Comment by lights0123** [comment]
@Paul-Reed you need to call the `.toString()` method of the `String`. So your code would be

```
if (load.toString() >= 7) {
```

And yes, `load` should be declared as a `String`.

**Comment by Paul-Reed** [comment]
Thank you @lights0123 
I can't believe that something that simple caused me so many problems!
`load.toInt()` certainly worked fine, and I've just added the full sketch to this repo.
The sketch appears to be working fine, and is running on a ESP Wemos mini in my greenhouse, controlling an irrigation pump, ensuring that my crops are kept healthy.
The interface is done in node-red, with all the data being fed from the ESP via MQTT QoS1. 

Thanks again for your help.

![screen](https://user-images.githubusercontent.com/973580/43711994-8b5c3548-996c-11e8-9048-32c168addb08.png)

**Comment by lights0123** [comment]
No problem! Glad to help. One thing though: I don't know if this is when transferring to GitHub, but it looks like you're missing a set of curly braces [here](https://github.com/Paul-Reed/imroy_mqtt_esp/blob/bbfaa8433da81bd90c3954330d076aca12c12e23/imroy_mqtt_esp.ino#L99).

**Comment by Paul-Reed** [comment]
Ooops! added in now, thank you.

Paul
